/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[9];
new PlayerText:PlayerTD[MAX_PLAYERS][19];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(418.000000, 155.000000, "_");
	TextDrawFont(PublicTD[0], 1);
	TextDrawLetterSize(PublicTD[0], 0.612500, 28.249973);
	TextDrawTextSize(PublicTD[0], 313.500000, 320.500000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 2);
	TextDrawColor(PublicTD[0], -1);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 255);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(418.000000, 148.000000, "INVENTORY (SKIN)");
	TextDrawFont(PublicTD[1], 2);
	TextDrawLetterSize(PublicTD[1], 0.191661, 1.299996);
	TextDrawTextSize(PublicTD[1], 397.000000, 321.000000);
	TextDrawSetOutline(PublicTD[1], 1);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 2);
	TextDrawColor(PublicTD[1], -1);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 255);
	TextDrawUseBox(PublicTD[1], 1);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(587.000000, 268.000000, ">");
	TextDrawFont(PublicTD[2], 1);
	TextDrawLetterSize(PublicTD[2], 0.625000, 1.599997);
	TextDrawTextSize(PublicTD[2], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[2], 1);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 2);
	TextDrawColor(PublicTD[2], -1);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], -2016478465);
	TextDrawUseBox(PublicTD[2], 1);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 1);

	PublicTD[3] = TextDrawCreate(247.000000, 268.000000, "<");
	TextDrawFont(PublicTD[3], 1);
	TextDrawLetterSize(PublicTD[3], 0.625000, 1.599997);
	TextDrawTextSize(PublicTD[3], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 2);
	TextDrawColor(PublicTD[3], -1);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], -2016478465);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 1);

	PublicTD[4] = TextDrawCreate(596.000000, 164.000000, "all");
	TextDrawFont(PublicTD[4], 2);
	TextDrawLetterSize(PublicTD[4], 0.191667, 1.100000);
	TextDrawTextSize(PublicTD[4], 11.000000, 30.000000);
	TextDrawSetOutline(PublicTD[4], 1);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 2);
	TextDrawColor(PublicTD[4], -1);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 255);
	TextDrawUseBox(PublicTD[4], 1);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 1);

	PublicTD[5] = TextDrawCreate(596.000000, 178.000000, "skin");
	TextDrawFont(PublicTD[5], 2);
	TextDrawLetterSize(PublicTD[5], 0.191667, 1.100000);
	TextDrawTextSize(PublicTD[5], 11.000000, 30.000000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 2);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 255);
	TextDrawUseBox(PublicTD[5], 1);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 1);

	PublicTD[6] = TextDrawCreate(596.000000, 192.000000, "accs");
	TextDrawFont(PublicTD[6], 2);
	TextDrawLetterSize(PublicTD[6], 0.191667, 1.100000);
	TextDrawTextSize(PublicTD[6], 11.000000, 30.000000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 2);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 255);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 1);

	PublicTD[7] = TextDrawCreate(596.000000, 206.000000, "misc");
	TextDrawFont(PublicTD[7], 2);
	TextDrawLetterSize(PublicTD[7], 0.191667, 1.100000);
	TextDrawTextSize(PublicTD[7], 11.000000, 30.000000);
	TextDrawSetOutline(PublicTD[7], 1);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 2);
	TextDrawColor(PublicTD[7], -1);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], 255);
	TextDrawUseBox(PublicTD[7], 1);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 1);

	PublicTD[8] = TextDrawCreate(416.000000, 26.000000, "Preview_Model");
	TextDrawFont(PublicTD[8], 5);
	TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[8], 71.500000, 104.000000);
	TextDrawSetOutline(PublicTD[8], 0);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 1);
	TextDrawColor(PublicTD[8], -1);
	TextDrawBackgroundColor(PublicTD[8], 85);
	TextDrawBoxColor(PublicTD[8], 255);
	TextDrawUseBox(PublicTD[8], 0);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);
	TextDrawSetPreviewModel(PublicTD[8], 4524);
	TextDrawSetPreviewRot(PublicTD[8], -10.000000, 0.000000, -20.000000, 0.000000);
	TextDrawSetPreviewVehCol(PublicTD[8], 27, 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 260.000000, 163.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][0], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][0], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][0], 1, 1);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 324.000000, 163.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], -86);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 1097458175);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][1], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][1], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][1], 1, 1);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 388.000000, 163.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], -86);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][2], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][2], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][2], 1, 1);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 452.000000, 163.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], -16777046);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][3], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][3], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][3], 1, 1);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 516.000000, 163.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 65450);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 65535);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][4], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][4], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][4], 1, 1);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 260.000000, 245.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][5], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][5], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][5], 1, 1);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 324.000000, 245.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][6], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][6], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][6], 1, 1);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 388.000000, 245.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][7], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][7], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][7], 1, 1);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 452.000000, 245.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][8], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][8], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][8], 1, 1);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 516.000000, 245.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][9], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][9], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][9], 1, 1);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 260.000000, 328.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][10], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][10], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][10], 1, 1);

	PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 324.000000, 328.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][11], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][11], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][11], 1, 1);

	PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 388.000000, 328.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][12], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][12], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][12], 1, 1);

	PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 452.000000, 328.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][13], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][13], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][13], 1, 1);

	PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 516.000000, 328.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 61.000000, 79.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], -1811885142);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][14], 189);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][14], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][14], 1, 1);

	PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 125.000000, 165.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 107.500000, 131.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 125);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][15], 294);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][15], -10.000000, 0.000000, -10.000000, 0.920000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][15], 1, 1);

	PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 179.000000, 148.000000, "tin");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.341666, 1.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 400.000000, 105.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][16], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

	PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 229.000000, 298.000000, "level: 69 (42.4)~n~124.24 played hours~n~bank: $4.252.252");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.166666, 1.049998);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 400.000000, 106.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 3);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

	PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 564.000000, 147.000000, "ld_beat:cross");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 13.000000, 14.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][18], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 1);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][11]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][12]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][13]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][14]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][15]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][16]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][17]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][18]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][11]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][12]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][13]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][14]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][15]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][16]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][17]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][18]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
