/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[19];
new PlayerText:PlayerTD[MAX_PLAYERS][20];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(186.500000, 144.000000, "_");
	TextDrawFont(PublicTD[0], 1);
	TextDrawLetterSize(PublicTD[0], -0.050000, 1.249981);
	TextDrawTextSize(PublicTD[0], 0.000000, 96.500000);
	TextDrawSetOutline(PublicTD[0], 0);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 2);
	TextDrawColor(PublicTD[0], -1);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 55);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(321.000000, 158.000000, "_");
	TextDrawFont(PublicTD[1], 1);
	TextDrawLetterSize(PublicTD[1], -0.050000, 18.349979);
	TextDrawTextSize(PublicTD[1], 0.000000, 365.500000);
	TextDrawSetOutline(PublicTD[1], 0);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 2);
	TextDrawColor(PublicTD[1], 255);
	TextDrawBackgroundColor(PublicTD[1], -16776961);
	TextDrawBoxColor(PublicTD[1], 55);
	TextDrawUseBox(PublicTD[1], 1);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(163.000000, 182.000000, "_");
	TextDrawFont(PublicTD[2], 0);
	TextDrawLetterSize(PublicTD[2], 0.600000, 7.449995);
	TextDrawTextSize(PublicTD[2], 298.500000, 47.500000);
	TextDrawSetOutline(PublicTD[2], 1);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 2);
	TextDrawColor(PublicTD[2], -1);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 9145223);
	TextDrawUseBox(PublicTD[2], 1);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(163.000000, 254.000000, "_");
	TextDrawFont(PublicTD[3], 1);
	TextDrawLetterSize(PublicTD[3], 0.600000, 7.449995);
	TextDrawTextSize(PublicTD[3], 298.500000, 47.500000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 2);
	TextDrawColor(PublicTD[3], -1);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], -65383);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 0);

	PublicTD[4] = TextDrawCreate(135.000000, 183.000000, "samaps:map");
	TextDrawFont(PublicTD[4], 5);
	TextDrawLetterSize(PublicTD[4], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[4], 56.500000, 67.500000);
	TextDrawSetOutline(PublicTD[4], 1);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], -1);
	TextDrawBackgroundColor(PublicTD[4], -256);
	TextDrawBoxColor(PublicTD[4], -1378294222);
	TextDrawUseBox(PublicTD[4], 0);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 0);
	TextDrawSetPreviewModel(PublicTD[4], 19784);
	TextDrawSetPreviewRot(PublicTD[4], -91.000000, 0.000000, 180.000000, 1.000000);
	TextDrawSetPreviewVehCol(PublicTD[4], 1, 1);

	PublicTD[5] = TextDrawCreate(135.000000, 252.000000, "samaps:map");
	TextDrawFont(PublicTD[5], 5);
	TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[5], 56.500000, 67.500000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 1);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], -256);
	TextDrawBoxColor(PublicTD[5], -1378294222);
	TextDrawUseBox(PublicTD[5], 0);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 0);
	TextDrawSetPreviewModel(PublicTD[5], 19785);
	TextDrawSetPreviewRot(PublicTD[5], -91.000000, 0.000000, 180.000000, 1.000000);
	TextDrawSetPreviewVehCol(PublicTD[5], 1, 1);

	PublicTD[6] = TextDrawCreate(163.000000, 146.000000, "Tier");
	TextDrawFont(PublicTD[6], 2);
	TextDrawLetterSize(PublicTD[6], 0.316666, 1.299998);
	TextDrawTextSize(PublicTD[6], 240.000000, 46.500000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 2);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], -1523963137);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	PublicTD[7] = TextDrawCreate(210.000000, 146.000000, "missions");
	TextDrawFont(PublicTD[7], 2);
	TextDrawLetterSize(PublicTD[7], 0.216664, 1.200000);
	TextDrawTextSize(PublicTD[7], 15.000000, 46.500000);
	TextDrawSetOutline(PublicTD[7], 1);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 2);
	TextDrawColor(PublicTD[7], -1);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], -1523963137);
	TextDrawUseBox(PublicTD[7], 1);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 1);

	PublicTD[8] = TextDrawCreate(164.000000, 160.000000, "1");
	TextDrawFont(PublicTD[8], 3);
	TextDrawLetterSize(PublicTD[8], 0.429165, 1.750000);
	TextDrawTextSize(PublicTD[8], 240.000000, 48.500000);
	TextDrawSetOutline(PublicTD[8], 1);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 2);
	TextDrawColor(PublicTD[8], -1);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], -1523963137);
	TextDrawUseBox(PublicTD[8], 1);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);

	PublicTD[9] = TextDrawCreate(326.000000, 120.000000, "battlepass gtavlc season ~r~1");
	TextDrawFont(PublicTD[9], 3);
	TextDrawLetterSize(PublicTD[9], 0.383332, 1.899999);
	TextDrawTextSize(PublicTD[9], 400.000000, 202.000000);
	TextDrawSetOutline(PublicTD[9], 1);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 2);
	TextDrawColor(PublicTD[9], -1);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], 50);
	TextDrawUseBox(PublicTD[9], 0);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 0);

	PublicTD[10] = TextDrawCreate(221.000000, 159.000000, "1");
	TextDrawFont(PublicTD[10], 3);
	TextDrawLetterSize(PublicTD[10], 0.429165, 1.850000);
	TextDrawTextSize(PublicTD[10], 242.500000, 62.000000);
	TextDrawSetOutline(PublicTD[10], 1);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 2);
	TextDrawColor(PublicTD[10], -1);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], -1962934017);
	TextDrawUseBox(PublicTD[10], 1);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 0);

	PublicTD[11] = TextDrawCreate(284.000000, 159.000000, "2");
	TextDrawFont(PublicTD[11], 3);
	TextDrawLetterSize(PublicTD[11], 0.429165, 1.850000);
	TextDrawTextSize(PublicTD[11], 242.500000, 62.000000);
	TextDrawSetOutline(PublicTD[11], 1);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 2);
	TextDrawColor(PublicTD[11], -1);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], -1523963137);
	TextDrawUseBox(PublicTD[11], 1);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 0);

	PublicTD[12] = TextDrawCreate(347.000000, 159.000000, "3");
	TextDrawFont(PublicTD[12], 3);
	TextDrawLetterSize(PublicTD[12], 0.429165, 1.850000);
	TextDrawTextSize(PublicTD[12], 242.500000, 62.000000);
	TextDrawSetOutline(PublicTD[12], 1);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 2);
	TextDrawColor(PublicTD[12], -1);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], -1962934017);
	TextDrawUseBox(PublicTD[12], 1);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 0);

	PublicTD[13] = TextDrawCreate(411.000000, 159.000000, "4");
	TextDrawFont(PublicTD[13], 3);
	TextDrawLetterSize(PublicTD[13], 0.429165, 1.850000);
	TextDrawTextSize(PublicTD[13], 242.500000, 62.000000);
	TextDrawSetOutline(PublicTD[13], 1);
	TextDrawSetShadow(PublicTD[13], 0);
	TextDrawAlignment(PublicTD[13], 2);
	TextDrawColor(PublicTD[13], -1);
	TextDrawBackgroundColor(PublicTD[13], 255);
	TextDrawBoxColor(PublicTD[13], -1523963137);
	TextDrawUseBox(PublicTD[13], 1);
	TextDrawSetProportional(PublicTD[13], 1);
	TextDrawSetSelectable(PublicTD[13], 0);

	PublicTD[14] = TextDrawCreate(472.000000, 159.000000, "5");
	TextDrawFont(PublicTD[14], 3);
	TextDrawLetterSize(PublicTD[14], 0.429165, 1.850000);
	TextDrawTextSize(PublicTD[14], 242.500000, 62.000000);
	TextDrawSetOutline(PublicTD[14], 1);
	TextDrawSetShadow(PublicTD[14], 0);
	TextDrawAlignment(PublicTD[14], 2);
	TextDrawColor(PublicTD[14], -1);
	TextDrawBackgroundColor(PublicTD[14], 255);
	TextDrawBoxColor(PublicTD[14], -1962934017);
	TextDrawUseBox(PublicTD[14], 1);
	TextDrawSetProportional(PublicTD[14], 1);
	TextDrawSetSelectable(PublicTD[14], 0);

	PublicTD[15] = TextDrawCreate(457.000000, 338.000000, "season ends: 31 days");
	TextDrawFont(PublicTD[15], 2);
	TextDrawLetterSize(PublicTD[15], 0.191666, 1.200001);
	TextDrawTextSize(PublicTD[15], 400.000000, 108.000000);
	TextDrawSetOutline(PublicTD[15], 1);
	TextDrawSetShadow(PublicTD[15], 0);
	TextDrawAlignment(PublicTD[15], 2);
	TextDrawColor(PublicTD[15], -1);
	TextDrawBackgroundColor(PublicTD[15], 255);
	TextDrawBoxColor(PublicTD[15], 50);
	TextDrawUseBox(PublicTD[15], 0);
	TextDrawSetProportional(PublicTD[15], 1);
	TextDrawSetSelectable(PublicTD[15], 0);

	PublicTD[16] = TextDrawCreate(138.000000, 326.000000, "your t?e is ~r~1(0.00%)~n~~w~click on a prize to see more info");
	TextDrawFont(PublicTD[16], 2);
	TextDrawLetterSize(PublicTD[16], 0.187499, 1.299998);
	TextDrawTextSize(PublicTD[16], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[16], 1);
	TextDrawSetShadow(PublicTD[16], 0);
	TextDrawAlignment(PublicTD[16], 1);
	TextDrawColor(PublicTD[16], -1);
	TextDrawBackgroundColor(PublicTD[16], 255);
	TextDrawBoxColor(PublicTD[16], 50);
	TextDrawUseBox(PublicTD[16], 0);
	TextDrawSetProportional(PublicTD[16], 1);
	TextDrawSetSelectable(PublicTD[16], 0);

	PublicTD[17] = TextDrawCreate(128.000000, 225.000000, "<");
	TextDrawFont(PublicTD[17], 3);
	TextDrawLetterSize(PublicTD[17], 0.479166, 1.850000);
	TextDrawTextSize(PublicTD[17], 12.500000, 17.000000);
	TextDrawSetOutline(PublicTD[17], 1);
	TextDrawSetShadow(PublicTD[17], 0);
	TextDrawAlignment(PublicTD[17], 2);
	TextDrawColor(PublicTD[17], -1);
	TextDrawBackgroundColor(PublicTD[17], 255);
	TextDrawBoxColor(PublicTD[17], 50);
	TextDrawUseBox(PublicTD[17], 0);
	TextDrawSetProportional(PublicTD[17], 1);
	TextDrawSetSelectable(PublicTD[17], 1);

	PublicTD[18] = TextDrawCreate(513.000000, 225.000000, ">");
	TextDrawFont(PublicTD[18], 3);
	TextDrawLetterSize(PublicTD[18], 0.479166, 1.850000);
	TextDrawTextSize(PublicTD[18], 12.500000, 17.000000);
	TextDrawSetOutline(PublicTD[18], 1);
	TextDrawSetShadow(PublicTD[18], 0);
	TextDrawAlignment(PublicTD[18], 2);
	TextDrawColor(PublicTD[18], -1);
	TextDrawBackgroundColor(PublicTD[18], 255);
	TextDrawBoxColor(PublicTD[18], 50);
	TextDrawUseBox(PublicTD[18], 0);
	TextDrawSetProportional(PublicTD[18], 1);
	TextDrawSetSelectable(PublicTD[18], 1);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	TextDrawDestroy(PublicTD[13]);
	TextDrawDestroy(PublicTD[14]);
	TextDrawDestroy(PublicTD[15]);
	TextDrawDestroy(PublicTD[16]);
	TextDrawDestroy(PublicTD[17]);
	TextDrawDestroy(PublicTD[18]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 190.000000, 180.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 1687547236);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 16777215);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][0], 4524);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][0], 0.000000, 0.000000, 0.000000, 0.319997);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][0], 1, 1);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 253.000000, 180.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 1097458010);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 55);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][1], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][1], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][1], 1, 1);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 316.000000, 180.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 1687547236);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 16777215);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][2], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][2], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][2], 1, 1);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 379.000000, 180.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 1097458010);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 55);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][3], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][3], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][3], 1, 1);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 442.000000, 180.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 1687547236);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 16777215);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][4], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][4], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][4], 1, 1);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 190.000000, 252.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], -2686876);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], -8388353);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][5], 4524);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][5], 0.000000, 0.000000, 0.000000, 0.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][5], 1, 1);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 253.000000, 252.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], -8433539);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][6], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][6], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][6], 1, 1);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 316.000000, 252.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], -2686876);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], -8388353);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][7], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][7], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][7], 1, 1);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 379.000000, 252.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], -8433539);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][8], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][8], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][8], 1, 1);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 442.000000, 252.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 61.500000, 71.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], -2686876);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], -8388353);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][9], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][9], 0.000000, 0.000000, 0.000000, 0.819998);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][9], 1, 1);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 221.000000, 205.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 1);

	PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 284.000000, 205.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 1);

	PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 348.000000, 205.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 1);

	PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 411.000000, 205.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 1);

	PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 474.000000, 205.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 1);

	PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 221.000000, 279.000000, "$2.000.000 IN BANK");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 1);

	PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 284.000000, 278.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][16], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 1);

	PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 348.000000, 278.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 1);

	PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 411.000000, 278.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][18], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 1);

	PlayerTD[playerid][19] = CreatePlayerTextDraw(playerid, 474.000000, 278.000000, "$500.000 in bank");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][19], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][19], 0.166666, 1.200000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][19], 15.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][19], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][19], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][19], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][19], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][19], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][19], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][19], 1);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][11]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][12]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][13]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][14]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][15]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][16]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][17]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][18]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][19]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		TextDrawShowForPlayer(playerid, PublicTD[13]);
		TextDrawShowForPlayer(playerid, PublicTD[14]);
		TextDrawShowForPlayer(playerid, PublicTD[15]);
		TextDrawShowForPlayer(playerid, PublicTD[16]);
		TextDrawShowForPlayer(playerid, PublicTD[17]);
		TextDrawShowForPlayer(playerid, PublicTD[18]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][11]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][12]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][13]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][14]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][15]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][16]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][17]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][18]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][19]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
